const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = 'https://acbiuzxkxnsbqyekytdi.supabase.co';
const supabaseKey = 'sb_publishable_i1HdlKcDVO9M61j5hb1DFA_hyLF2z2F';
const supabase = createClient(supabaseUrl, supabaseKey);

async function createTable() {
  console.log("Attempting to create schemes table...");
  const sql = `
    CREATE TABLE IF NOT EXISTS public.schemes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      scheme_name TEXT NOT NULL,
      category TEXT NOT NULL,
      description TEXT NOT NULL,
      eligibility_criteria TEXT,
      documents_required TEXT,
      benefits TEXT,
      steps_for_applying TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `;

  // Note: Supabase's standard JS client doesn't support raw SQL execution easily 
  // via the anon key unless a Postgres function is created first. 
  // But we can try using RPC if there's an `exec_sql` function (rare),
  // OR we can just try to insert a dummy record and see if the table exists,
  // returning instructions if it doesn't.
  
  const { data, error } = await supabase.from('schemes').select('*').limit(1);
  if (error && error.code === 'PGRST205') {
    console.log("Table 'schemes' does not exist.");
    console.log("Unfortunately, I cannot execute raw DDL (CREATE TABLE) statements directly through the Supabase JavaScript Anon Client for security reasons.");
    console.log("The user MUST run the SQL in their Supabase dashboard.");
  } else if (error) {
    console.log("Other error:", error);
  } else {
    console.log("Table 'schemes' exists and is ready!");
  }
}

createTable();
